import React, { useState, useMemo } from 'react';

const QuickActions = ({ employees, employeeDatabase, onBulkUpdate, darkMode }) => {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedDepartment, setSelectedDepartment] = useState('');
  const [bulkAction, setBulkAction] = useState('');
  const [selectedEmployees, setSelectedEmployees] = useState([]);

  const departments = useMemo(() => {
    const depts = [...new Set(employees.map(emp => emp.departmentName || emp.costCentre).filter(Boolean))];
    return depts.sort();
  }, [employees]);

  const filteredEmployees = useMemo(() => {
    return employees.filter(emp => {
      const matchesSearch = emp.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           emp.email?.toLowerCase().includes(searchTerm.toLowerCase()) ||
                           emp.employeeId?.toLowerCase().includes(searchTerm.toLowerCase());
      const matchesDept = !selectedDepartment || emp.departmentName === selectedDepartment || emp.costCentre === selectedDepartment;
      return matchesSearch && matchesDept;
    });
  }, [employees, searchTerm, selectedDepartment]);

  const employeeHistory = useMemo(() => {
    const history = {};
    employees.forEach(emp => {
      const key = emp.employeeId || emp.email || emp.name;
      if (!history[key]) {
        history[key] = {
          employee: emp,
          trainings: []
        };
      }
      history[key].trainings.push(emp);
    });
    return history;
  }, [employees]);

  const handleBulkAction = () => {
    if (!bulkAction || selectedEmployees.length === 0) {
      alert('Please select employees and an action');
      return;
    }

    const action = bulkAction;
    const count = selectedEmployees.length;
    
    if (window.confirm(`Are you sure you want to ${action} for ${count} selected employees?`)) {
      // In a real system, this would update the backend
      alert(`✅ Successfully applied "${action}" to ${count} employees!`);
      setSelectedEmployees([]);
      setBulkAction('');
    }
  };

  const generateMonthlyReport = () => {
    const currentMonth = new Date().toISOString().slice(0, 7);
    const monthlyData = employees.filter(emp => emp.date?.startsWith(currentMonth));
    
    const report = {
      month: currentMonth,
      totalEmployees: monthlyData.length,
      totalHours: monthlyData.reduce((sum, emp) => sum + emp.hours, 0),
      totalDaysLost: monthlyData.reduce((sum, emp) => sum + emp.daysLost, 0),
      departments: {}
    };

    monthlyData.forEach(emp => {
      const dept = emp.departmentName || emp.costCentre || 'Unknown';
      if (!report.departments[dept]) {
        report.departments[dept] = { employees: 0, hours: 0, daysLost: 0 };
      }
      report.departments[dept].employees++;
      report.departments[dept].hours += emp.hours;
      report.departments[dept].daysLost += emp.daysLost;
    });

    // Create and download report
    const reportContent = `
MONTHLY TRAINING REPORT - ${currentMonth}
==========================================

SUMMARY:
- Total Employees Trained: ${report.totalEmployees}
- Total Training Hours: ${report.totalHours}
- Total Days Lost: ${report.totalDaysLost.toFixed(2)}

DEPARTMENT BREAKDOWN:
${Object.entries(report.departments).map(([dept, data]) => 
  `${dept}: ${data.employees} employees, ${data.hours} hours, ${data.daysLost.toFixed(2)} days lost`
).join('\n')}

Generated: ${new Date().toLocaleString()}
Generated by: Rachel's HR Analytics Hub
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Monthly-Training-Report-${currentMonth}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    alert('📊 Monthly report generated and downloaded!');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className={`p-6 rounded-xl ${darkMode ? 'bg-gradient-to-r from-gray-800 to-gray-900' : 'bg-gradient-to-r from-purple-600 to-indigo-700'} text-white`}>
        <h1 className="text-3xl font-bold mb-2">⚡ Quick Actions Panel</h1>
        <p className="text-purple-100">Bulk operations, employee lookup, and instant reports</p>
      </div>

      {/* Quick Reports */}
      <div className={`p-6 rounded-lg ${darkMode ? 'bg-gray-800' : 'bg-white'} shadow-lg`}>
        <h2 className={`text-xl font-semibold mb-4 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
          📊 One-Click Reports
        </h2>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button
            onClick={generateMonthlyReport}
            className="p-4 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <div className="text-2xl mb-2">📅</div>
            <div className="font-semibold">Monthly Summary</div>
            <div className="text-sm opacity-90">Current month training data</div>
          </button>
          
          <button
            onClick={() => alert('🚧 Quarterly report feature coming soon!')}
            className="p-4 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
          >
            <div className="text-2xl mb-2">📈</div>
            <div className="font-semibold">Quarterly Trends</div>
            <div className="text-sm opacity-90">3-month comparison</div>
          </button>
          
          <button
            onClick={() => alert('🚧 Compliance report feature coming soon!')}
            className="p-4 bg-red-600 text-white rounded-lg hover:bg-red-700 transition-colors"
          >
            <div className="text-2xl mb-2">🎯</div>
            <div className="font-semibold">Compliance Status</div>
            <div className="text-sm opacity-90">Department compliance</div>
          </button>
        </div>
      </div>

      {/* Employee Lookup */}
      <div className={`p-6 rounded-lg ${darkMode ? 'bg-gray-800' : 'bg-white'} shadow-lg`}>
        <h2 className={`text-xl font-semibold mb-4 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
          🔍 Quick Employee Lookup
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <input
            type="text"
            placeholder="Search by name, email, or ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className={`px-4 py-2 rounded-lg border ${darkMode ? 'bg-gray-700 text-white border-gray-600' : 'bg-white border-gray-300'}`}
          />
          <select
            value={selectedDepartment}
            onChange={(e) => setSelectedDepartment(e.target.value)}
            className={`px-4 py-2 rounded-lg border ${darkMode ? 'bg-gray-700 text-white border-gray-600' : 'bg-white border-gray-300'}`}
          >
            <option value="">All Departments</option>
            {departments.map(dept => (
              <option key={dept} value={dept}>{dept}</option>
            ))}
          </select>
        </div>

        <div className="max-h-64 overflow-y-auto space-y-2">
          {filteredEmployees.slice(0, 10).map((emp, index) => (
            <div key={index} className={`p-3 rounded border ${darkMode ? 'border-gray-700 bg-gray-700' : 'border-gray-200 bg-gray-50'} hover:shadow-md transition-shadow`}>
              <div className="flex justify-between items-start">
                <div>
                  <h3 className={`font-semibold ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                    {emp.name}
                  </h3>
                  <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                    {emp.employeeId} • {emp.email} • {emp.departmentName || emp.costCentre}
                  </p>
                </div>
                <div className="text-right">
                  <div className="text-sm font-medium text-red-600">
                    {emp.daysLost.toFixed(1)} days lost
                  </div>
                  <div className={`text-xs ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                    {emp.hours} hours • {emp.date}
                  </div>
                </div>
              </div>
            </div>
          ))}
          {filteredEmployees.length === 0 && (
            <div className={`text-center py-8 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
              <div className="text-4xl mb-2">🔍</div>
              <p>No employees found matching your search</p>
            </div>
          )}
        </div>
      </div>

      {/* Bulk Operations */}
      <div className={`p-6 rounded-lg ${darkMode ? 'bg-gray-800' : 'bg-white'} shadow-lg`}>
        <h2 className={`text-xl font-semibold mb-4 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
          ⚡ Bulk Operations
        </h2>
        
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <select
            value={bulkAction}
            onChange={(e) => setBulkAction(e.target.value)}
            className={`px-4 py-2 rounded-lg border ${darkMode ? 'bg-gray-700 text-white border-gray-600' : 'bg-white border-gray-300'}`}
          >
            <option value="">Select Bulk Action</option>
            <option value="Mark as Completed">Mark Training as Completed</option>
            <option value="Send Reminder">Send Training Reminder</option>
            <option value="Schedule Follow-up">Schedule Follow-up Training</option>
            <option value="Generate Certificates">Generate Certificates</option>
            <option value="Update Status">Update Training Status</option>
          </select>
          
          <button
            onClick={handleBulkAction}
            disabled={!bulkAction || selectedEmployees.length === 0}
            className={`px-4 py-2 rounded-lg transition-colors ${
              bulkAction && selectedEmployees.length > 0
                ? 'bg-orange-600 text-white hover:bg-orange-700'
                : 'bg-gray-400 text-gray-200 cursor-not-allowed'
            }`}
          >
            Apply to {selectedEmployees.length} Selected
          </button>
        </div>

        <div className="space-y-2 max-h-48 overflow-y-auto">
          {employees.slice(0, 15).map((emp, index) => (
            <label key={index} className={`flex items-center p-2 rounded cursor-pointer hover:${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}>
              <input
                type="checkbox"
                checked={selectedEmployees.includes(emp.id)}
                onChange={(e) => {
                  if (e.target.checked) {
                    setSelectedEmployees(prev => [...prev, emp.id]);
                  } else {
                    setSelectedEmployees(prev => prev.filter(id => id !== emp.id));
                  }
                }}
                className="mr-3"
              />
              <div className="flex-1">
                <span className={`font-medium ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                  {emp.name}
                </span>
                <span className={`ml-2 text-sm ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                  {emp.departmentName || emp.costCentre} • {emp.daysLost.toFixed(1)} days
                </span>
              </div>
            </label>
          ))}
        </div>

        <div className="mt-4 flex gap-2">
          <button
            onClick={() => setSelectedEmployees(employees.map(emp => emp.id))}
            className="px-3 py-1 text-sm bg-blue-600 text-white rounded hover:bg-blue-700"
          >
            Select All
          </button>
          <button
            onClick={() => setSelectedEmployees([])}
            className="px-3 py-1 text-sm bg-gray-600 text-white rounded hover:bg-gray-700"
          >
            Clear Selection
          </button>
        </div>
      </div>
    </div>
  );
};

export default QuickActions;